Algoritmo "Maior, menor ou iqual a 20 "

// Descrição   : Identifica se o numero e igual ou maior ou menor que 20
// Autor(a)    : Sabrina
// Data atual  : 28/12/2022

Var

numero:real

Inicio

escreval("Digite um numero:")
leia(numero)

se (numero <= 20) entao
escreval("O valor digitado e menor ou igual a 20")
senao
escreval("O valor digitado e maior que 20")
fimse

Fimalgoritmo
