Algoritmo "Olá, Mundo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/12/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


escreval ("Ola Mundo!")


escreval ("O ditado popular do dia e")
escreval ("Um dia e da caça, o outro e do caçador.")



Fimalgoritmo